---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: candlepin
spec:
  containers:
  - name: candlepin
    image: quay.io/candlepin/candlepin:4.3.12-1
    env:
    - name: POSTGRESQL_DB_HOST
      value: quadlet-demo-mysql
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-root-password-kube
          key: password
  volumes:
  - name: config-volume
    configMap:
      name: envoy-proxy-config
  - name: certificates
    secret:
      secretName: envoy-certificates
  - name: candlepin-persistent-storage
    persistentVolumeClaim:
      claimName: wp-pv-claim
