---
- name: Create the podman secret for Candlepin CA certificate
  containers.podman.podman_secret:
    name: candlepin-ca-cert
    path: "{{ candlepin_ca_certificate }}"
    state: present

- name: Create the podman secret for Candlepin CA key
  containers.podman.podman_secret:
    name: candlepin-ca-key
    path: "{{ candlepin_ca_key }}"
    state: present
