---
- name: Setup quadlet demo machine
  hosts: all
  become: true
  vars:
    candlepin_db_password: "{{ lookup('community.general.random_string', special=false, length=20) }}"
    candlepin_artemis_client_dn: "CN=katello"
    candlepin_ca_key: "{{ certificates_ca_directory }}/private/ca.key"
    candlepin_ca_certificate: "{{ certificates_ca_directory }}/certs/ca.crt"
    postgresql_databases:
    - name: candlepin
    postgresql_users:
      - name: candlepin
        password: "{{ candlepin_db_password }}"
        db: candlepin
  roles:
    - certificates
    - geerlingguy.postgresql
    - candlepin
