---
- name: Setup quadlet demo machine
  hosts: all
  become: true
  vars:
    candlepin_db_password: "{{ lookup('community.general.random_string', special=false, length=20) }}"
    candlepin_artemis_client_dn: "CN=katello"
  pre_tasks:
  - name: Upgrade all packages
    ansible.builtin.package:
      name: "*"
      state: latest
    register: result
    retries: 5
    until: result is success

  - name: Install packages
    ansible.builtin.package:
      name:
      - podman
      - python3-cryptography
      - bash-completion

  - name: Populate service facts
    ansible.builtin.service_facts:

  - name: Open Ports in firewalld
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
    loop:
    - 23443/tcp
    when:
    - services['firewalld.service'] is defined
    - services['firewalld.service']['state'] == 'running'
